## [Develop Your First Neural Network in Python With Keras Step-By-Step](http://machinelearningmastery.com/tutorial-first-neural-network-python-keras/)

### Tutorial courtesy of Jason Brownlee -- Thank You Jason!!

### Docs can be found at https://keras.io/

In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy

Using TensorFlow backend.


## 1. Load Data

In [2]:
# Fix random seed for reproducibility.
seed = 7
numpy.random.seed(seed)

In [3]:
# Load Pima Indians Diabetes dataset from UCI Machine Learning repository.
# http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
dataset

array([[   6.   ,  148.   ,   72.   , ...,    0.627,   50.   ,    1.   ],
       [   1.   ,   85.   ,   66.   , ...,    0.351,   31.   ,    0.   ],
       [   8.   ,  183.   ,   64.   , ...,    0.672,   32.   ,    1.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,    0.245,   30.   ,    0.   ],
       [   1.   ,  126.   ,   60.   , ...,    0.349,   47.   ,    1.   ],
       [   1.   ,   93.   ,   70.   , ...,    0.315,   23.   ,    0.   ]])

In [4]:
# Split dataset into input (X) and output (Y) variables.
X = dataset[:,0:8]
Y = dataset[:,8]

In [5]:
X

array([[   6.   ,  148.   ,   72.   , ...,   33.6  ,    0.627,   50.   ],
       [   1.   ,   85.   ,   66.   , ...,   26.6  ,    0.351,   31.   ],
       [   8.   ,  183.   ,   64.   , ...,   23.3  ,    0.672,   32.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,   26.2  ,    0.245,   30.   ],
       [   1.   ,  126.   ,   60.   , ...,   30.1  ,    0.349,   47.   ],
       [   1.   ,   93.   ,   70.   , ...,   30.4  ,    0.315,   23.   ]])

In [6]:
Y

array([ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0

## 2. Define Model

In [7]:
# Create Model.
# The first, input, layer has 12 neurons and expects 8 input variables.
# The second, hidden, layer has 8 neurons.
# The third, output, layer has 1 neuron to predict the class (onset of diabetes or not).
model = Sequential()
model.add(Dense(12, input_dim=8, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

## 3. Compile Model

In [8]:
# Compile model.
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## 4. Fit Model

In [9]:
# Fit the model.
# This is the part where your CPU/GPU gets a workout.
model.fit(X, Y, nb_epoch=150, batch_size=10)

Epoch 1/150
768/768 [==============================] - 0s - loss: 0.6838 - acc: 0.6107     
Epoch 2/150
768/768 [==============================] - 0s - loss: 0.6652 - acc: 0.6510     
Epoch 3/150
768/768 [==============================] - 0s - loss: 0.6520 - acc: 0.6497     
Epoch 4/150
768/768 [==============================] - 0s - loss: 0.6379 - acc: 0.6536     
Epoch 5/150
768/768 [==============================] - 0s - loss: 0.6170 - acc: 0.6732     
Epoch 6/150
768/768 [==============================] - 0s - loss: 0.6084 - acc: 0.6875     
Epoch 7/150
768/768 [==============================] - 0s - loss: 0.6028 - acc: 0.6784     
Epoch 8/150
768/768 [==============================] - 0s - loss: 0.5962 - acc: 0.6966     
Epoch 9/150
768/768 [==============================] - 0s - loss: 0.5942 - acc: 0.6823     
Epoch 10/150
768/768 [==============================] - 0s - loss: 0.5892 - acc: 0.6953     
Epoch 11/150
768/768 [==============================] - 0s - loss: 0.5895 - acc

## 5. Evaluate Model

In [10]:
# Evaluate the model.
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

448/768 [================>.............] - ETA: 0sacc: 78.65%


## 6. Tie It All Together

In [11]:
# Create first network with Keras
from keras.models import Sequential
from keras.layers import Dense
import numpy
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X, Y, nb_epoch=150, batch_size=10)
# evaluate the model
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/150
768/768 [==============================] - 0s - loss: 0.6839 - acc: 0.6120     
Epoch 2/150
768/768 [==============================] - 0s - loss: 0.6654 - acc: 0.6510     
Epoch 3/150
768/768 [==============================] - 0s - loss: 0.6533 - acc: 0.6497     
Epoch 4/150
768/768 [==============================] - 0s - loss: 0.6409 - acc: 0.6497     
Epoch 5/150
768/768 [==============================] - 0s - loss: 0.6230 - acc: 0.6667     
Epoch 6/150
768/768 [==============================] - 0s - loss: 0.6146 - acc: 0.6823     
Epoch 7/150
768/768 [==============================] - 0s - loss: 0.6086 - acc: 0.6771     
Epoch 8/150
768/768 [==============================] - 0s - loss: 0.6008 - acc: 0.6810     
Epoch 9/150
768/768 [==============================] - 0s - loss: 0.5963 - acc: 0.6966     
Epoch 10/150
768/768 [==============================] - 0s - loss: 0.5905 - acc: 0.6914     
Epoch 11/150
768/768 [==============================] - 0s - loss: 0.5906 - acc

## 7. Bonus: Make Predictions

In [12]:
# This is a complete example that makes predictions for each record in the training data.

# Create first network with Keras
from keras.models import Sequential
from keras.layers import Dense
import numpy
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X, Y, nb_epoch=150, batch_size=10,  verbose=2)
# calculate predictions
predictions = model.predict(X)
# round predictions
rounded = [numpy.round(x[0]) for x in predictions]
print(rounded)

Epoch 1/150
0s - loss: 0.6843 - acc: 0.6133
Epoch 2/150
0s - loss: 0.6651 - acc: 0.6510
Epoch 3/150
0s - loss: 0.6533 - acc: 0.6497
Epoch 4/150
0s - loss: 0.6411 - acc: 0.6497
Epoch 5/150
0s - loss: 0.6244 - acc: 0.6641
Epoch 6/150
0s - loss: 0.6146 - acc: 0.6797
Epoch 7/150
0s - loss: 0.6082 - acc: 0.6797
Epoch 8/150
0s - loss: 0.6011 - acc: 0.6849
Epoch 9/150
0s - loss: 0.5973 - acc: 0.6927
Epoch 10/150
0s - loss: 0.5913 - acc: 0.6862
Epoch 11/150
0s - loss: 0.5909 - acc: 0.6901
Epoch 12/150
0s - loss: 0.5891 - acc: 0.6979
Epoch 13/150
0s - loss: 0.5860 - acc: 0.6875
Epoch 14/150
0s - loss: 0.5788 - acc: 0.6966
Epoch 15/150
0s - loss: 0.5750 - acc: 0.7005
Epoch 16/150
0s - loss: 0.5707 - acc: 0.7031
Epoch 17/150
0s - loss: 0.5848 - acc: 0.6953
Epoch 18/150
0s - loss: 0.5796 - acc: 0.6914
Epoch 19/150
0s - loss: 0.5766 - acc: 0.7044
Epoch 20/150
0s - loss: 0.5745 - acc: 0.6940
Epoch 21/150
0s - loss: 0.5727 - acc: 0.7096
Epoch 22/150
0s - loss: 0.5722 - acc: 0.6953
Epoch 23/150
0s - l